/*
 * Testdriver source generated by TESSY
 *
 * (c) Razorcat Development GmbH
 *
 * DO NOT EDIT THIS FILE !
 *
 *
 * File          : Slave Header (ts_is_value_in_range_s.h)
 * Testpath      : C:/Users/Sowjanya/Desktop/GIT_FO~1/tessy\work\00000401\00000402\00000403\00000404
 * Modulename    : Sample
 * Testobjectname: is_value_in_range
 * Date          : 04.06.2020
 * Time          : 10:12:00
 * Tessy Version : 4.2.8
 *
 */

#if !defined (__TS_SLAVE_H)
   #define __TS_SLAVE_H


#endif /* !defined __TS_SLAVE_H */
